import type { Metadata } from "next";
import Link from "next/link";
import { ContactDetails, DocumentLayout } from "@/components/document-layout";

export const metadata: Metadata = { title: "Terms of use", description: "Moodimo’s app license, Apple purchase information, and terms for using this website.", alternates: { canonical: "/terms/" } };

export default function Terms() {
  return <DocumentLayout eyebrow="THE IMPORTANT THINGS" title="A few simple terms." intro="The essentials about using Moodimo, its website, and any optional purchases." updated sections={[{ id: "license", title: "App license" }, { id: "purchases", title: "Optional purchases" }, { id: "journal", title: "Your journal" }, { id: "website", title: "Website & contact" }]}>
    <section id="license"><h2>1. The app’s license</h2><p>Moodimo is licensed under <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple’s Standard Licensed Application End User License Agreement</a>, unless a different license is explicitly provided with your App Store download. That agreement sets out the terms of the app license. This page summarizes practical information and does not replace Apple’s agreement or limit any rights you have under applicable consumer law.</p><p>Moodimo is for personal journaling, reflection, and organization. It does not provide medical advice, diagnosis, or treatment.</p></section>
    <section id="purchases"><h2>2. Optional purchases & subscriptions</h2><p>Moodimo Pro is in development. When paid products become available, the app and Apple’s purchase confirmation will show the current price, billing period, and any trial terms before you confirm a purchase. No purchase can be made through this website.</p><p>Apple processes App Store payments. An auto-renewing subscription continues until canceled according to Apple’s displayed terms. Manage or cancel it through <a href="https://apps.apple.com/account/subscriptions">your Apple Account subscriptions</a>. Deleting the app does not cancel billing. Refund requests are handled through <a href="https://reportaproblem.apple.com/">Apple’s Report a Problem service</a>, subject to Apple’s policies and applicable law.</p><p>Where available, use Restore Purchases in the app to restore eligible purchases associated with your Apple Account. Product availability and final feature allowances will be described in the app at launch.</p></section>
    <section id="journal"><h2>3. Your journal stays yours</h2><p>You keep your rights to the content you create. Moodimo uses your content to provide the features you choose. Our <Link href="/privacy/">privacy policy</Link> explains local storage, optional iCloud sync, permissions, and deletion.</p><p>Keep backups of entries you want to preserve. Exported backups are not encrypted by Moodimo, and iCloud sync also propagates deletions. A sync service is not a substitute for an independent backup.</p></section>
    <section id="website"><h2>4. This website & getting in touch</h2><p>The site introduces an app that is still being prepared for release. Interactive examples use sample content and do not create a real journal. Features and availability may change during development. The artwork, wordmark, and site design are provided to present Moodimo; third-party fonts and software retain their own licenses.</p><ContactDetails /></section>
  </DocumentLayout>;
}
