import type { Metadata } from "next";
import { ContactDetails, DocumentLayout, PolicyStatus } from "@/components/document-layout";

export const metadata: Metadata = { title: "Privacy policy", description: "How Euthymo handles your journal, optional iCloud sync, Apple purchases, backups, and website visits.", alternates: { canonical: "/privacy/" } };

const sections = [
  { id: "overview", title: "The short version" }, { id: "journal", title: "Your journal & device" },
  { id: "icloud", title: "Optional iCloud sync" }, { id: "permissions", title: "Permissions & reminders" },
  { id: "purchases", title: "Apple purchases" }, { id: "retention", title: "Keeping & deleting data" },
  { id: "website", title: "This website" }, { id: "support", title: "Support & your choices" },
  { id: "children", title: "Children’s privacy" }, { id: "changes", title: "Changes & contact" },
];

export default function Privacy() {
  return <DocumentLayout eyebrow="YOUR INNER WORLD. YOURS TO KEEP." title="Privacy, in plain language." intro="Your feelings belong to you. Here’s how Euthymo handles the information in your journal, and what happens when you visit this website." updated sections={sections}>
    <PolicyStatus />
    <section id="overview"><div className="document-summary"><p><strong>The short version:</strong> Euthymo saves your journal on your device. There is no Euthymo account, advertising, or third-party tracking SDK. We do not operate a server that receives your journal. If you turn on iCloud sync, your journal also goes to your private iCloud database. Purchases are handled by Apple.</p></div><p>This policy covers the Euthymo app for iPhone, iPad, and Mac, and the website at www.euthymo.com. “We” refers to the developer of Euthymo. Information handled by Apple and the website’s hosting provider is also subject to their own privacy policies, as described below.</p></section>
    <section id="journal"><h2>1. Your journal & your device</h2><p>Euthymo stores the content you choose to create in the app. This can include moods, journal text, photos, voice recordings, drawings, stickers and canvas layouts, activities, energy and sleep observations, habits, to-dos, goals, rewards, drafts, edit history, and preferences such as a display name.</p><p>This information is used on your device to display your journal, calculate habit and goal progress, and show insights from your own entries. Euthymo does not send your journal to an advertising service, analytics provider, or remote AI service. We do not sell your journal or use it for advertising.</p><p>The app uses your device’s date and timezone to organize days and reminders. It does not request GPS location for these features. The website’s interactive examples contain invented entries and keep your selections only in the current page’s memory; they are not saved as a journal or sent to us.</p><h3>App lock</h3><p>If you enable app lock, the operating system authenticates you using the available device unlock method, such as Face ID, Touch ID, a device passcode, or a Mac password. Euthymo receives the authentication result, not your biometric data or password. App lock controls access inside the app; it does not separately encrypt exported backups or recovery copies.</p></section>
    <section id="icloud"><h2>2. Optional iCloud sync</h2><p>iCloud sync is off unless you choose to enable it. When enabled, Euthymo uses Apple’s CloudKit service and your private iCloud database to keep your journal and supported preferences in step across your devices signed into the same Apple Account. This includes journal attachments when present. Device-specific app lock and reminder settings do not sync.</p><p>The implementation uses CloudKit encrypted record fields and encrypts larger journal payloads before uploading them. Euthymo does not receive your Apple Account password and does not route this content through a developer-operated server. Apple provides the iCloud infrastructure under its <a href="https://www.apple.com/legal/privacy/">privacy policy</a> and <a href="https://www.apple.com/legal/internet-services/icloud/">iCloud terms</a>.</p><p>You can turn sync off in Settings → iCloud sync and choose whether to keep the iCloud copy or delete it. Turning off sync keeps the journal already stored on this device. Deleting the iCloud copy does not automatically remove existing local copies on your other devices. iCloud sync is separate from the operating system’s device backups.</p></section>
    <section id="permissions"><h2>3. Permissions & reminders</h2><ul><li><strong>Photos:</strong> the system photo picker lets you choose the images to add. Euthymo imports the selected images into your journal, rather than uploading your photo library to us.</li><li><strong>Camera:</strong> if you choose to take a photo in the app, camera access is used to capture that journal attachment.</li><li><strong>Microphone:</strong> microphone access is used when you choose to record a voice note. Recordings are stored with your journal.</li><li><strong>Notifications:</strong> with your permission, Euthymo schedules reminders locally through the operating system. Notifications use generic text by default; text you choose to display may be visible on your lock screen.</li></ul><p>You can change the relevant permissions in your device’s system settings and change reminder schedules or text inside Euthymo. Declining a permission prevents the corresponding optional feature; it does not prevent you from writing a journal. Removing a permission does not delete attachments you have already saved.</p></section>
    <section id="purchases"><h2>4. Purchases & subscriptions</h2><p>If you choose a paid Euthymo product when available, Apple handles the payment through the App Store. Euthymo uses StoreKit transaction information, such as the product purchased, expiration, and revocation status, to determine which features are available. The app does not receive or store your full payment card details.</p><p>Apple may provide the developer with sales, financial, crash, or other reports under Apple’s services and your device settings. These reports are separate from your journal; Euthymo does not attach your journal content to them. Apple controls the data it processes for your Apple Account, purchases, and device diagnostics. See <a href="https://www.apple.com/legal/privacy/">Apple’s privacy policy</a>.</p><p>Subscriptions and cancellation are managed through your Apple Account. Deleting Euthymo or your journal does not cancel a subscription. Use <a href="https://apps.apple.com/account/subscriptions">Apple’s subscription management</a> to review or cancel a plan.</p></section>
    <section id="retention"><h2>5. Keeping, exporting & deleting data</h2><p>Your local journal remains on your device until you remove the relevant content or clear app data. Euthymo does not apply a developer-server retention period to your journal because we do not hold a copy on our servers.</p><ul><li><strong>Journal entries:</strong> deleting an entry moves it to Trash. Permanently deleting it from Trash removes it from the active archive, along with related edit history and drafts handled by the app.</li><li><strong>Clear all data:</strong> Settings → Backup & data → Clear all data clears the active journal. When iCloud sync is on, the change also syncs to your other connected devices.</li><li><strong>Recovery copies:</strong> Euthymo keeps local copies before certain restores or migrations to help protect against data loss. These copies can contain the complete previous journal and remain until you separately delete them in Settings. Clearing the active journal does not remove recovery copies.</li><li><strong>Exported backups:</strong> exports contain your archive, which may include journal media, drafts, Trash, and edit history. Euthymo exports are not encrypted by the app. Copies you save or share remain in those locations until you delete them there.</li><li><strong>iCloud and device backups:</strong> you can delete Euthymo’s synced iCloud copy through the app’s iCloud settings. Device backups, Time Machine backups, and other independent copies are managed separately through the relevant Apple or backup service.</li></ul><p>We cannot recover, read, or delete a journal stored only on your device on your behalf. Before removing the app or changing devices, export a backup if you want to keep your entries. Share or store that file only where you intend your journal to be available.</p></section>
    <section id="website"><h2>6. Visiting this website</h2><p>This website does not use advertising pixels, analytics scripts, tracking cookies, or a newsletter form. Fonts and illustrations are served with the site, rather than loaded from a third-party font or image service. The interactive previews do not use cookies or browser storage to remember your mood or task selections.</p><p>This website is hosted on a Hostinger virtual private server. Delivering the site requires processing technical connection information, such as your IP address and requested page. Routine access logging is disabled in the website’s web server, and the shared reverse proxy has no access logging configured. Technical error logs from the website container rotate at 1 MB per file, with up to three files retained. Shared server operational logs are separate and remain until rotated or removed during maintenance. Hostinger may also process infrastructure and security information under its <a href="https://www.hostinger.com/legal/privacy-policy">privacy policy</a>. These hosting records are separate from the Euthymo app and do not contain your in-app journal.</p><p>If you follow a link to Apple or another external website, that service receives your visit under its own policies. Our website does not embed those external pages.</p></section>
    <section id="support"><h2>7. Support & your choices</h2><p>If you contact us at bijbrin@gmail.com, Google’s Gmail service delivers your message under <a href="https://policies.google.com/privacy">Google’s privacy policy</a>. We receive the email address and the message or attachments you send. We use that information to answer your request and address the issue you report. Please send only the details needed for support; a full journal backup is not required for an ordinary question.</p><p>Support correspondence is kept while it is needed to resolve your request and handle necessary follow-up or legal obligations, and is then deleted when no longer needed. Depending on where you live, you may have rights to request access, correction, or deletion of personal information held by us, or to raise a concern with a privacy regulator. Contact us to exercise those rights. Information controlled by Apple is managed through Apple’s own privacy tools.</p><p>For your journal itself, you have direct controls to review and edit entries, export a backup, delete content, turn off iCloud sync, and withdraw system permissions. There is no Euthymo account database to close or off-device journal record for us to search.</p></section>
    <section id="children"><h2>8. Children’s privacy</h2><p>Euthymo is a personal reflection app and is not designed to collect children’s personal information through a developer-run account or service. If you believe a child has sent us personal information through a support message, contact us so we can review and address it. Parents and guardians can manage app permissions, purchases, and device access using Apple’s family and device controls.</p></section>
    <section id="changes"><h2>9. Changes & contact</h2><p>We will update this page when our data practices change and revise the date above. If a future change requires permission, we will ask before enabling the relevant data use. This policy describes Euthymo’s current implementation and this website.</p><ContactDetails /></section>
  </DocumentLayout>;
}
